#ifndef __YAOOC_UNIQUE_INDEX_ARRAY_CONTAINER_INCLUDED__
#define __YAOOC_UNIQUE_INDEX_ARRAY_CONTAINER_INCLUDED__

#include <yaooc/index_array_container.h>

class_table(yaooc_unique_index_array_container)
{
  yaooc_index_array_container_class_members_t;
};

class_instance(yaooc_unique_index_array_container)
{
	yaooc_index_array_container_instance_members_t;
};

class(yaooc_unique_index_array_container);
ISA_DEFINITION(yaooc_unique_index_array_container,yaooc_index_array_container)
// Container contructors
// args: 1- const type_info_t*
#define yaooc_unique_index_array_container_ctor yaooc_index_array_container_ctor
#define yaooc_unique_index_array_container_internal_ctor yaooc_index_array_container_internal_ctor
void yaooc_index_array_container_resize(pointer,yaooc_size_type,const_pointer);
#define yaooc_unique_index_array_container_reserve yaooc_index_array_container_reserve
#define yaooc_unique_index_array_container_clear   yaooc_array_container_clear
#define yaooc_unique_index_array_container_shrink_to_fit yaooc_index_array_container_shrink_to_fit
#define yaooc_unique_index_array_container_at yaooc_array_container_at
#define yaooc_unique_index_array_container_cat yaooc_array_container_cat
#define yaooc_unique_index_array_container_size yaooc_array_container_size
#define yaooc_unique_index_array_container_capacity yaooc_array_container_capacity
#define yaooc_unique_index_array_container_empty yaooc_array_container_empty
#define yaooc_unique_index_array_container_clear yaooc_array_container_clear
#define yaooc_unique_index_array_container_begin yaooc_array_container_begin
#define yaooc_unique_index_array_container_end yaooc_array_container_end
#define yaooc_unique_index_array_container_cbegin yaooc_array_container_cbegin
#define yaooc_unique_index_array_container_cend yaooc_array_container_cend
#define yaooc_unique_index_array_container_get_type_info yaooc_array_container_get_type_info

iterator yaooc_unique_index_array_container_insert(pointer,const_iterator,const_pointer); //,yaooc_size_type n);  // insert n elements starting a pos
iterator yaooc_unique_index_array_container_insert_range(pointer,const_iterator,const_iterator,const_iterator);
iterator yaooc_unique_index_array_container_insert_n(pointer,const_iterator,yaooc_size_type,const_pointer);
#define yaooc_unique_index_array_container_erase yaooc_index_array_container_erase
#define yaooc_unique_index_array_container_erase_range yaooc_index_array_container_erase_range

#define yaooc_unique_index_array_container_find yaooc_index_array_container_find
#define yaooc_unique_index_array_container_cfind yaooc_index_array_container_cfind

#define yaooc_index_array_container_default_ctor yaooc_array_container_default_ctor

#define YAOOC_UNIQUE_INDEX_ARRAY_CONTAINER_CLASS_MEMBERS \
  { \
    YAOOC_INDEX_ARRAY_CONTAINER_CLASS_MEMBERS \
  }

#endif
