== Inheritance
For a "%struct", inheritance is implemented as follows:

[source,c]
-----------------------------
%struct class_name : parent_name {
  ...
};
-----------------------------
A "%struct" inherits all instance entries of the parent.

For "%class", a parent is required ("%struct" does not require a parent). If not specified, the parent will be "yaooc_object". For simplicity, let's assume that "yaooc_object" is defined as follows.

[source,c]
-----------------------------
%class yaooc_object {
  table:
    void swap(pointer s) { }
};
-----------------------------

A class inherits all instance and table members. Table and instance members can be overriden. An overridden method should have the same return type, name, and argument types.

For the my_string class, the swap method will be overridden with the following:

[source,c]
-----------------------------
%class my_string : yaooc_object {
    ...
  instance:
    ...
  table:
    void swap(pointer o)
    {
      my_string_pointer other=o;  // "o" is a generic pointer, must use my_string_pointer
      char* temp=this->str;
      this->str=other->str;
      other->str=temp;
    }
};
-----------------------------

Note the the swap method uses a generic pointer (void *) as an argument.
A pointer of the appropriate type must be defined.

Although possible (if you understand the inner workings of YAOOC),
a struct should not have a class as a parent and a class should not have a struct as a parent.

=== Calling Parent Method
For methods defined in the table section of a class, two macros are defined to allow a parent method to be called.

The "super()" macro is used to call the parent method of the same name and arguments.
For example, in the "swap" method for my_string, "super()" would call the yaooc_object "swap" method.

The "PM" (parent method) macro is used to call any other parent method. It's syntax is "PM(method,args)"

=== Type declarations
When a class is inherited from another class, the behaviour of default constructor, destructor, etc is as follows.

==== Default Constructor
If a default contructor is defined, YAOOC uses it.
If a default constructor is not defined, YAOOC will traverse the inheritance tree (parent, grand parent, etc) until a default constructor is found. If not found (user specified "delete" for this and ancestor default constructors), no action is taken.

==== Destructor
When an object is deleted, each destructor in reverse order of inheritance (the child destructor, the parent destructor, the grandparent destructor, etc) will be called until the root class is reached. The destrutor should only destory the portion of the object that was initialized at the current level of inheritance.
The ancestors will destroy their portions.

==== Copy Constructor
Like the default constructor, YAOOC will traverse the inheritance tree until a defined copy constructor is found.
If not found, then the instance is copied (using memcpy).

==== Assignment
Like the copy constructor, YAOOC will traverse the inheritance tree until a defined assignment method is found.
If not found, then the instance is copied (using memcpy).

==== Rich compare
YAOOC will traverse the inheritance tree until a rich compare method is found.
If none is found, then it would be as if 0 were returned.

==== To/From stream
Like rich compare, YAOOC traverses the inheritance tree until a to/from stream method is found.
If none found, then an exception is thrown.
