== YAOOCPP Rules
Just one more thing before going back to developing the my_string class.
This lesson will reveal the rules that YAOOCPP uses for creating default versions of default constructor, destructor, copy constructor, and assignment.
YAOOCPP does not create default versions of rich compare and stream input/output.

=== Default Constructor
If not specified or the "=default" option is used, YAOOCPP will create a default constructor using the following rules.

.YAOOCPP Rules for creating default constructor
* If there aren't any new variables defined in the instance sub section, then a default constructor will not be created.
* The parent (or first defined ancestor default constructor) is called.
* For each new variable defined.
** If the variable type is a pointer (the variable type ends with "*"), the variable is set to NULL;
** If the variable type is a YAOOC static object (the variable type ends with "_t"), newp is used to initilize the variable.
** Otherwise, the variable is set to 0 (zero).

Going back to our first simple class definition of my_string

[source,c]
----------------------
%struct my_string {
  instance:
    char* str;
};
----------------------

The following default constructor would be created.

[source,c]
----------------------
my_string() {
  call_parent_default_ctor(this);
  this->str=NULL;
}
----------------------
=== Destructor
If not specified or the "=default" option is used, YAOOCPP will create a destructor using the following rules.

.YAOOCPP Rules for creating destructor
* If there aren't any new variables defined in the instance sub section, then a destructor will not be created.
* For each new variable defined.
** If the variable type is a non const pointer (the variable type does not begin with "const" and ends with "*"), then "free" is called with variable as argument;
** If the variable type is a YAOOC dynamic object (the variable type ends with "_t*"), delete is used to destroy the variable.
** If the variable type is a YAOOC static object (the variable type ends with "_t"), deletep is used to destroy the variable.
** Otherwise, no action is taken.

The following destructor would have been created for the simple version of my_string class.

[source,c]
----------------------
~my_string() {
  if(this->str!=NULL)
    free(this->str);
}
----------------------

=== Copy Constructor
If not specified or the "=default" option is used, YAOOCPP will create a copy constructor using the following rules.

.YAOOCPP Rules for creating Copy Constructor
* If there aren't any new variables defined in the instance sub section, then a copy constructor will not be created.
* The default constructor for the class is called followed by a call to assignment method.

The following copy constructor would have been created for the simple version of my_string class.

[source,c]
----------------------
my_string(src) : my_string() {
  assign_static(this,src,my_string); // call assignment method
}
----------------------

=== Assignment
If not specified or the "=default" option is used, YAOOCPP will create an assignment method using the following rules.

.YAOOCPP Rules for creating Assignment Method
* If there aren't any new variables defined in the instance sub section, then an assignment method will not be created.
* For each new variable defined.
** If the variable type is a not const pointer to a YAOOC object (the variable type does not begin with "const" and ends with "_t*"), then assignment is done using assignment method -- assign(this->var,src->var)
** If the variable type is a YAOOC static object (the variable type ends with "_t"), assign_static is used to assign the variable.
** Otherwise, assigned the variable using C assignment -- this->var = src->var.

The following assignment method would have been created for the simple version of my_string class.

[source,c]
----------------------
operator=(src) {
  this->str=src->str;  // This is most likely NOT what is desired since both objects use the same allocated memory
}
----------------------

=== Rich compare and to/from stream
Default methods are not provided for rich compare and to/from stream.
